// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartVestFinancialAdvisor.Data;

#nullable disable

namespace SmartVestFinancialAdvisor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421204428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartVestFinancialAdvisor.Data.SurveyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PortfolioJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SurveySubmissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveySubmissionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SurveyResults_UserId");

                    b.HasIndex("UserId", "ComputedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_SurveyResults_UserId_ComputedAt");

                    b.ToTable("SurveyResults");
                });

            modelBuilder.Entity("SmartVestFinancialAdvisor.Data.SurveySubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptionIv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SurveySubmissions_UserId");

                    b.HasIndex("UserId", "SubmittedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_SurveySubmissions_UserId_SubmittedAt");

                    b.ToTable("SurveySubmissions");
                });

            modelBuilder.Entity("SmartVestFinancialAdvisor.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasCompletedSurvey")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSurveySubmitAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email_Unique");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartVestFinancialAdvisor.Data.SurveyResult", b =>
                {
                    b.HasOne("SmartVestFinancialAdvisor.Data.SurveySubmission", "SurveySubmission")
                        .WithMany()
                        .HasForeignKey("SurveySubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartVestFinancialAdvisor.Data.User", "User")
                        .WithMany("SurveyResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SurveySubmission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartVestFinancialAdvisor.Data.SurveySubmission", b =>
                {
                    b.HasOne("SmartVestFinancialAdvisor.Data.User", "User")
                        .WithMany("SurveySubmissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartVestFinancialAdvisor.Data.User", b =>
                {
                    b.Navigation("SurveyResults");

                    b.Navigation("SurveySubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
